### ISSUE TITLE
Code_11_3.cs doesn't compile

### ISSUE THREAD

**Issue by zizo2006** [PacktPublishing/Hands-On-Object-Oriented-Programming-with-CSharp#1]
I'm using VS 2019 and create console .Net Core application with target framework .net Core 3.0. The sample is giving me compilation errors

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS1503	Argument 1: cannot convert from 'System.Collections.Generic.IEnumerable<int>' to 'System.Collections.Generic.IAsyncEnumerable<int>'	AsyncStreams	C:\Users\mohamed.abdelaziz\source\repos\AsyncStreams\AsyncStreams\Program.cs	13		Active
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	AsyncStreams	C:\Users\mohamed.abdelaziz\source\repos\AsyncStreams\AsyncStreams\CSC	1		Active

**Comment by raihantaher** [comment]
Hi @zizo2006 

Sorry for late reply. Not sure if you have already figured out the issue or not. From the error it looks like a type conversion issue. 

`cannot convert from 'System.Collections.Generic.IEnumerable' to 'System.Collections.Generic.IAsyncEnumerable' `

Can you please check your code if you are using the correct type.

If still not working, please post your code here so that i can see.

Thanks

**Comment by garora** [comment]
@zizo2006 - The method `GetSumOfNums` expects parameter of type `IAsyncEnumerable` but `IEnumerable` was supplied, so you get the error. I made changes to the code. This code is working for both `.NET Core 3.0` and `.NET Core 3.1`
[AsyncStreamConsoleSample.zip](https://github.com/PacktPublishing/Hands-On-Object-Oriented-Programming-with-CSharp/files/5086704/AsyncStreamConsoleSample.zip)
